# Generated by Django 5.0.1 on 2024-01-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('published', models.DateTimeField(verbose_name='Fecha de estreno')),
                ('videotitle', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'estreno',
                'verbose_name_plural': 'estrenos',
                'ordering': ['-created'],
            },
        ),
    ]
