# Generated by Django 5.0.1 on 2024-01-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='published',
            field=models.DateField(verbose_name='Fecha de estreno'),
        ),
    ]
