# Generated by Django 5.0.1 on 2024-01-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_alter_feature_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL VIDEO'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='videotitle',
            field=models.CharField(max_length=100, verbose_name='T´tulo Video'),
        ),
    ]
