# Generated by Django 5.0.1 on 2024-01-18 14:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_alter_feature_url_alter_feature_videotitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
